// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using infiniteworlds_frontend.Data;

#nullable disable

namespace infiniteworlds_fronted.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241001142226_Updateuserprofilegenerate")]
    partial class Updateuserprofilegenerate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin-id",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ce95e522-511b-4353-b697-3cf0f17392c5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cceef6f8-cc0b-402f-a589-3af5956143fb",
                            Email = "Priscilla.Sawayn14@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "beaueiui",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "26792993-5b05-44b0-9e6f-3736b5a17084",
                            TwoFactorEnabled = false,
                            UserName = "Cicero45"
                        },
                        new
                        {
                            Id = "29fc2edf-dc5d-4e0f-aaf3-ebb8b5e72f96",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fa41b197-ea22-4197-9118-f9d90efbae92",
                            Email = "Michaela25@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "dioiuiau",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1058bc2a-4828-4093-aff5-b91ebeab0489",
                            TwoFactorEnabled = false,
                            UserName = "Kaelyn88"
                        },
                        new
                        {
                            Id = "cabe5f4b-2b82-4d96-8455-7c3f7f656293",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2dc1739a-c2bf-4d3f-b35f-77d35ed54925",
                            Email = "Keeley_Heathcote30@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "teiiaeuo",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f6278c27-d45c-4bb8-85a5-5f63570d76b9",
                            TwoFactorEnabled = false,
                            UserName = "Eleazar.Gottlieb20"
                        },
                        new
                        {
                            Id = "b8c57e6e-9a96-41f8-b45b-4dfaba5d3191",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "af0751fa-9b54-41e8-a4bd-7761be25e07e",
                            Email = "Helen6@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "qiiaouie",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dceeeaf4-7fdd-4de2-8886-17ca889b48a9",
                            TwoFactorEnabled = false,
                            UserName = "Salma_Hoppe17"
                        },
                        new
                        {
                            Id = "afd3af4b-7e26-4e7f-865c-56ce4e5c52d5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e06fef52-6af6-4211-805a-a2e6f420fd93",
                            Email = "Bruce.Upton99@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "nuoiaeoa",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0eadd52c-5621-457d-b4ee-8af49311dc02",
                            TwoFactorEnabled = false,
                            UserName = "Dolores73"
                        },
                        new
                        {
                            Id = "2a4603d7-1946-4c71-9994-46ba70f1d64a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1a39d709-ee1f-4c58-a250-ce57b4e995c0",
                            Email = "Sabrina57@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "yuiieaei",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0ddba573-c74e-429d-9062-f38b0ce24d4b",
                            TwoFactorEnabled = false,
                            UserName = "Ulises.Labadie"
                        },
                        new
                        {
                            Id = "8e0905d9-106b-44a4-9ef9-526a32d3cfdf",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e9857385-9f4f-4cb3-b99f-10e5c09e3e17",
                            Email = "Oswald_Sporer60@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "voioeioo",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "535b799d-4b3a-4725-ab01-87dbb1076d7b",
                            TwoFactorEnabled = false,
                            UserName = "Rosalee.Koss"
                        },
                        new
                        {
                            Id = "7ad9cb22-f79f-4e95-982b-29279f0296d6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ea3acab9-2bee-4f89-92c8-0aae860885b3",
                            Email = "Dayna9@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "kuoeuioe",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c2533805-61e4-4ecc-bc2b-04d6b2e08a86",
                            TwoFactorEnabled = false,
                            UserName = "Gordon_Gleichner"
                        },
                        new
                        {
                            Id = "c47ac2e4-2218-498f-8b7f-5f1dd9d4755c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "791a20a0-a415-4788-a75a-d8d66fd1263e",
                            Email = "Lucienne_Skiles8@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "pauuauao",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fc181bae-89b4-48c5-bc4e-ae7b7209ad72",
                            TwoFactorEnabled = false,
                            UserName = "Chauncey_Dicki67"
                        },
                        new
                        {
                            Id = "f07f192f-d7d4-4e12-afa5-0e6f4efcb640",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cb6281e5-823a-403f-856f-0c4b726b887f",
                            Email = "Reggie.Hahn@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "veeaoeia",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "77a31518-9f91-4023-a8b0-fedee53f5c28",
                            TwoFactorEnabled = false,
                            UserName = "Shanie30"
                        },
                        new
                        {
                            Id = "user-admin-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "86eafb0a-cb62-492e-9db2-c90d3627001a",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEO9CV/VdEGnBWamqVmQt7j9ZO84lGXrQ0C+JzopvqiBWhTmjaWG5ARRAd1tgkShwHQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-admin-id",
                            RoleId = "role-admin-id"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("infiniteworlds_fronted.Models.UserProfileViewModel", b =>
                {
                    b.Property<string>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserProfileId");

                    b.ToTable("userProfileViewModels");
                });

            modelBuilder.Entity("infiniteworlds_frontend.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFilePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Descripcion = "Et inventore aliquam quos eum voluptas est aut. Quas repellat quo. Necessitatibus cumque qui libero amet est voluptas maxime. Est quod consequatur molestiae delectus quia omnis impedit aut. Quia necessitatibus debitis quaerat. Rem dignissimos voluptatem error eveniet eum neque ratione quos laboriosam.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Practical Cotton Cheese",
                            ReleaseDate = new DateTime(2016, 10, 16, 10, 13, 14, 542, DateTimeKind.Local).AddTicks(5873)
                        },
                        new
                        {
                            GameId = 2,
                            Descripcion = "Sit aut voluptate consectetur aut sit dolorum esse nam maiores. Suscipit quos nulla nesciunt fuga accusantium rerum animi. Accusamus non aut praesentium et aut sint animi. Nemo fugiat saepe est natus corporis.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Intelligent Frozen Table",
                            ReleaseDate = new DateTime(2021, 10, 6, 13, 29, 0, 242, DateTimeKind.Local).AddTicks(2247)
                        },
                        new
                        {
                            GameId = 3,
                            Descripcion = "Repellat cumque aliquid rerum. Et dolores velit aut laboriosam aperiam. Sint reiciendis voluptas nulla harum sed eveniet voluptatum nobis autem.",
                            Genero = "Action",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Small Cotton Bike",
                            ReleaseDate = new DateTime(2020, 5, 26, 4, 51, 38, 641, DateTimeKind.Local).AddTicks(449)
                        },
                        new
                        {
                            GameId = 4,
                            Descripcion = "Explicabo repudiandae voluptates. Enim corrupti aut. Ex et modi et.",
                            Genero = "Shooter",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Unbranded Fresh Ball",
                            ReleaseDate = new DateTime(2023, 10, 17, 9, 34, 5, 280, DateTimeKind.Local).AddTicks(2403)
                        },
                        new
                        {
                            GameId = 5,
                            Descripcion = "Et sint dolore dolorem iure veritatis. Adipisci deleniti et quam consectetur inventore dolores maxime dolorem. Repellat cumque saepe. Commodi debitis id eaque.",
                            Genero = "Shooter",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Generic Wooden Hat",
                            ReleaseDate = new DateTime(2021, 6, 15, 3, 30, 10, 605, DateTimeKind.Local).AddTicks(1889)
                        },
                        new
                        {
                            GameId = 6,
                            Descripcion = "Animi molestiae sint beatae cupiditate adipisci aspernatur consectetur ullam. Quia accusamus dolores. Cum necessitatibus dolores accusamus ducimus aut. Ut sunt est ad aut nulla pariatur tenetur. Pariatur culpa nemo eveniet a incidunt asperiores.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Gorgeous Metal Car",
                            ReleaseDate = new DateTime(2022, 7, 4, 11, 19, 13, 713, DateTimeKind.Local).AddTicks(7918)
                        },
                        new
                        {
                            GameId = 7,
                            Descripcion = "Facere voluptas error unde et nesciunt molestias provident nihil magnam. Quia rerum rerum necessitatibus facilis quas. Hic aperiam corrupti.",
                            Genero = "Shooter",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Refined Rubber Mouse",
                            ReleaseDate = new DateTime(2015, 11, 5, 16, 49, 42, 534, DateTimeKind.Local).AddTicks(5349)
                        },
                        new
                        {
                            GameId = 8,
                            Descripcion = "Necessitatibus vero soluta vel excepturi. Molestiae nihil voluptas ut quia aut qui et. Enim suscipit magni rerum minus nemo sed deleniti quo.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Rustic Steel Shoes",
                            ReleaseDate = new DateTime(2022, 2, 20, 23, 20, 22, 342, DateTimeKind.Local).AddTicks(5628)
                        },
                        new
                        {
                            GameId = 9,
                            Descripcion = "Perspiciatis harum quia quaerat facilis. Reiciendis vitae dicta. Earum cumque cumque autem ab est. Tempore ut distinctio dignissimos quisquam. Ducimus omnis non. Aperiam reiciendis doloremque repellat perspiciatis.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Gorgeous Steel Towels",
                            ReleaseDate = new DateTime(2022, 1, 4, 18, 40, 18, 263, DateTimeKind.Local).AddTicks(1778)
                        },
                        new
                        {
                            GameId = 10,
                            Descripcion = "Aut odit at enim. Delectus repudiandae qui minus mollitia et aut. Veniam enim assumenda saepe. Blanditiis eius illo eveniet assumenda non provident neque explicabo voluptas.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Practical Frozen Fish",
                            ReleaseDate = new DateTime(2016, 10, 30, 13, 32, 39, 329, DateTimeKind.Local).AddTicks(6415)
                        },
                        new
                        {
                            GameId = 11,
                            Descripcion = "Accusamus eligendi qui est quisquam sed facilis est. Sed earum sed consequatur consectetur rem. Et accusantium magni fugit enim illum repudiandae vel.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Tasty Fresh Chair",
                            ReleaseDate = new DateTime(2018, 10, 8, 19, 43, 18, 911, DateTimeKind.Local).AddTicks(1677)
                        },
                        new
                        {
                            GameId = 12,
                            Descripcion = "Beatae necessitatibus iusto ut. Asperiores reprehenderit accusamus distinctio voluptatum ullam possimus dolore consectetur commodi. Saepe voluptates molestias ullam nemo. Ut atque quod animi enim magni sunt. Et eaque enim autem ratione doloremque eaque hic inventore. Velit perspiciatis et perspiciatis voluptate eveniet est quae repellendus.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Unbranded Concrete Pants",
                            ReleaseDate = new DateTime(2023, 10, 28, 19, 23, 12, 100, DateTimeKind.Local).AddTicks(4067)
                        },
                        new
                        {
                            GameId = 13,
                            Descripcion = "Quam explicabo aut dolorem accusantium excepturi nihil adipisci. Veniam rerum voluptatem eaque aspernatur dolore rerum sed eum. Qui et iste error asperiores non placeat. Tenetur dolorem consectetur aperiam molestias ea iusto a ipsum voluptates. Dolor odit maiores et at velit id quae. Rem ipsa sed eligendi ut minima ea reprehenderit tempore laborum.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Awesome Steel Fish",
                            ReleaseDate = new DateTime(2023, 2, 6, 14, 50, 6, 723, DateTimeKind.Local).AddTicks(5511)
                        },
                        new
                        {
                            GameId = 14,
                            Descripcion = "Ipsa tempore delectus et natus. Provident itaque cum ea natus. Commodi cum corrupti illo dolore dolore odio.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Handmade Concrete Soap",
                            ReleaseDate = new DateTime(2020, 3, 26, 2, 54, 3, 286, DateTimeKind.Local).AddTicks(5316)
                        },
                        new
                        {
                            GameId = 15,
                            Descripcion = "Aut corporis a repellat non sequi. Possimus et eaque assumenda. Minima nemo nisi laborum deserunt.",
                            Genero = "Action",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Tasty Plastic Bike",
                            ReleaseDate = new DateTime(2015, 12, 26, 23, 8, 5, 786, DateTimeKind.Local).AddTicks(6896)
                        },
                        new
                        {
                            GameId = 16,
                            Descripcion = "Ipsa distinctio est odit quisquam expedita optio omnis. Et autem et accusamus. Voluptatibus odit praesentium nobis. Amet sapiente soluta aut praesentium iusto nihil accusamus saepe dolorem. Dolore quam saepe cum vero. Ea occaecati dolore fugit accusantium.",
                            Genero = "Action",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Incredible Granite Ball",
                            ReleaseDate = new DateTime(2015, 3, 29, 20, 14, 24, 581, DateTimeKind.Local).AddTicks(2125)
                        },
                        new
                        {
                            GameId = 17,
                            Descripcion = "Vel quod assumenda cupiditate est dolorem iure. Et et dolorem. Numquam distinctio voluptatem alias consequatur odit qui nihil est minima. Voluptatum voluptas nihil. Ut consequatur accusantium provident.",
                            Genero = "Adventure",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Tasty Metal Sausages",
                            ReleaseDate = new DateTime(2024, 2, 6, 19, 49, 25, 949, DateTimeKind.Local).AddTicks(6745)
                        },
                        new
                        {
                            GameId = 18,
                            Descripcion = "Sit in quibusdam. Facere non eos voluptate eveniet ut vel ut reiciendis. Vel et molestiae rerum cum totam esse.",
                            Genero = "Action",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Tasty Cotton Soap",
                            ReleaseDate = new DateTime(2021, 1, 9, 20, 58, 32, 743, DateTimeKind.Local).AddTicks(8124)
                        },
                        new
                        {
                            GameId = 19,
                            Descripcion = "Non et eius quaerat neque harum sint explicabo. Voluptas architecto et facere voluptate suscipit nihil. Nisi commodi fuga et incidunt explicabo nulla voluptate.",
                            Genero = "Adventure",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Ergonomic Granite Gloves",
                            ReleaseDate = new DateTime(2018, 7, 11, 20, 27, 50, 371, DateTimeKind.Local).AddTicks(3294)
                        },
                        new
                        {
                            GameId = 20,
                            Descripcion = "Et possimus nobis similique ea dolores. Eaque et quo deserunt ea fugit id. Ipsum inventore accusantium ea. Facilis adipisci minus. Pariatur sequi vel sed eveniet et nam autem.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Rustic Granite Soap",
                            ReleaseDate = new DateTime(2019, 6, 11, 12, 36, 59, 117, DateTimeKind.Local).AddTicks(6720)
                        },
                        new
                        {
                            GameId = 21,
                            Descripcion = "Nulla aliquid facilis officiis consequatur quia. Voluptatem molestias minima. Ratione tempore quisquam. Ratione veniam consequatur. Quia laudantium harum sunt nam sequi exercitationem hic nostrum laboriosam. Enim et similique.",
                            Genero = "Shooter",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Ergonomic Steel Tuna",
                            ReleaseDate = new DateTime(2016, 6, 1, 5, 49, 42, 678, DateTimeKind.Local).AddTicks(9157)
                        },
                        new
                        {
                            GameId = 22,
                            Descripcion = "Qui numquam vel quis voluptatem quidem. In facere nulla quos rerum labore quod voluptas vitae. Incidunt voluptas distinctio praesentium voluptatum. Odit facilis cum rerum.",
                            Genero = "Shooter",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Licensed Metal Fish",
                            ReleaseDate = new DateTime(2015, 8, 16, 10, 28, 11, 434, DateTimeKind.Local).AddTicks(2563)
                        },
                        new
                        {
                            GameId = 23,
                            Descripcion = "Eveniet et sed ut et nihil molestiae. Dolores magnam officiis magni rerum provident consectetur aut. Voluptatem qui incidunt in cupiditate.",
                            Genero = "Action",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Generic Wooden Tuna",
                            ReleaseDate = new DateTime(2016, 9, 16, 13, 28, 50, 125, DateTimeKind.Local).AddTicks(65)
                        },
                        new
                        {
                            GameId = 24,
                            Descripcion = "Sint debitis sint iusto ut in. Consequuntur ipsum ea unde. Aut soluta accusantium nisi sit et dolorem. Officia iusto id unde velit quod excepturi. Aspernatur occaecati aut cupiditate. Voluptas itaque repellat vel omnis quis earum animi dolorum.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Small Wooden Table",
                            ReleaseDate = new DateTime(2023, 11, 2, 20, 12, 40, 428, DateTimeKind.Local).AddTicks(6727)
                        },
                        new
                        {
                            GameId = 25,
                            Descripcion = "Libero harum rerum dolores voluptatem ut id expedita et aut. Repellendus aliquid laborum doloribus expedita. Voluptatem doloribus sed accusantium omnis. Eveniet et quaerat tempore sed nobis.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Fantastic Concrete Pizza",
                            ReleaseDate = new DateTime(2024, 3, 17, 19, 13, 43, 554, DateTimeKind.Local).AddTicks(264)
                        },
                        new
                        {
                            GameId = 26,
                            Descripcion = "Perspiciatis est magni et corrupti culpa. Voluptatem veniam et. Hic omnis deserunt esse fuga sint autem. Voluptate explicabo molestias et quos. Harum molestiae numquam nihil facilis nihil magni cupiditate non. Nobis molestias aut fugiat omnis dolorem.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Handcrafted Granite Hat",
                            ReleaseDate = new DateTime(2024, 3, 5, 15, 38, 14, 140, DateTimeKind.Local).AddTicks(684)
                        },
                        new
                        {
                            GameId = 27,
                            Descripcion = "Voluptas velit praesentium quam ut qui dolorem debitis. Soluta adipisci mollitia id magni. Debitis sint quis sit.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Handmade Frozen Towels",
                            ReleaseDate = new DateTime(2018, 9, 19, 22, 16, 37, 410, DateTimeKind.Local).AddTicks(6670)
                        },
                        new
                        {
                            GameId = 28,
                            Descripcion = "Occaecati odit enim. Repellat temporibus quidem magni. Quia quod explicabo quia dolores quam. Et quo dolor quis nihil consequatur.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Handmade Frozen Chair",
                            ReleaseDate = new DateTime(2016, 12, 14, 19, 0, 7, 580, DateTimeKind.Local).AddTicks(145)
                        },
                        new
                        {
                            GameId = 29,
                            Descripcion = "Et dicta illum non quia mollitia. Officiis quas aliquam consequuntur mollitia corrupti sapiente omnis a. Voluptates fuga adipisci numquam animi magnam quia natus. Quia fugit et consequatur voluptate aspernatur commodi possimus et rerum.",
                            Genero = "Action",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Sleek Cotton Table",
                            ReleaseDate = new DateTime(2020, 2, 12, 4, 4, 14, 573, DateTimeKind.Local).AddTicks(6066)
                        },
                        new
                        {
                            GameId = 30,
                            Descripcion = "Non autem consequatur totam ut nemo. Molestias qui id aut quo porro voluptas et. Quod impedit mollitia ducimus iure voluptatem.",
                            Genero = "Action",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Gorgeous Wooden Soap",
                            ReleaseDate = new DateTime(2022, 1, 10, 13, 20, 50, 625, DateTimeKind.Local).AddTicks(539)
                        },
                        new
                        {
                            GameId = 31,
                            Descripcion = "Consequuntur nisi placeat excepturi doloribus eos ut. Porro excepturi velit consequatur officia architecto fuga est minima. Aut quas porro consequatur magnam atque vero delectus et eos. Architecto autem voluptas commodi et. Omnis maxime natus earum.",
                            Genero = "Adventure",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Sleek Rubber Mouse",
                            ReleaseDate = new DateTime(2023, 10, 28, 15, 6, 34, 394, DateTimeKind.Local).AddTicks(2325)
                        },
                        new
                        {
                            GameId = 32,
                            Descripcion = "Non rerum neque sit qui voluptas. Dolorem maiores qui eum aut. Repudiandae est autem numquam quia est veniam. Est sit distinctio totam.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Practical Frozen Cheese",
                            ReleaseDate = new DateTime(2022, 10, 25, 8, 55, 35, 412, DateTimeKind.Local).AddTicks(9573)
                        },
                        new
                        {
                            GameId = 33,
                            Descripcion = "Expedita consequuntur repellat labore harum dolorem quibusdam maxime. Et consequatur necessitatibus corporis veniam facere et rerum. Molestias sunt quisquam blanditiis est beatae ut aspernatur. Provident laudantium enim molestiae ullam vel illum. Voluptas nihil nisi totam exercitationem occaecati. Sit sunt maxime eum quod facere consequatur quia.",
                            Genero = "Adventure",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Refined Metal Mouse",
                            ReleaseDate = new DateTime(2023, 3, 28, 16, 35, 49, 544, DateTimeKind.Local).AddTicks(4406)
                        },
                        new
                        {
                            GameId = 34,
                            Descripcion = "Nostrum rerum corporis et molestiae eos et magnam et. Saepe illum natus neque incidunt sunt. Molestiae eveniet a aut aliquam labore. Veniam voluptas nesciunt fuga quas similique incidunt autem ut et. Asperiores quis incidunt aliquam sequi recusandae eos doloribus ut assumenda. Molestiae qui in.",
                            Genero = "Shooter",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Refined Metal Sausages",
                            ReleaseDate = new DateTime(2020, 10, 31, 0, 12, 37, 856, DateTimeKind.Local).AddTicks(3830)
                        },
                        new
                        {
                            GameId = 35,
                            Descripcion = "Sit nihil quam. Voluptas ut beatae et minus et amet ab deleniti beatae. Molestiae similique at sunt et blanditiis soluta omnis amet consequatur. Sed rerum adipisci doloremque omnis suscipit. Voluptatibus debitis corrupti corrupti dolorem rerum expedita.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Handcrafted Wooden Chicken",
                            ReleaseDate = new DateTime(2020, 12, 17, 0, 57, 30, 933, DateTimeKind.Local).AddTicks(9370)
                        },
                        new
                        {
                            GameId = 36,
                            Descripcion = "Amet totam corrupti rerum consectetur eos. Nisi velit vitae. Quaerat nihil libero libero non maxime qui ullam dolores. Delectus dignissimos assumenda fuga dolor. Ratione temporibus amet unde enim inventore ratione aliquid suscipit ut. Ut dolore sit perferendis nesciunt.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Handcrafted Frozen Pizza",
                            ReleaseDate = new DateTime(2018, 4, 27, 21, 5, 16, 292, DateTimeKind.Local).AddTicks(2168)
                        },
                        new
                        {
                            GameId = 37,
                            Descripcion = "Quis voluptatem tempore odit cumque. Neque consequatur esse quia aut rerum et quae sed voluptatem. Atque nihil qui aliquid aperiam quaerat tenetur laborum. Fugiat eveniet deserunt consectetur voluptas minus aliquid deleniti et.",
                            Genero = "Adventure",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Generic Cotton Chicken",
                            ReleaseDate = new DateTime(2020, 8, 2, 22, 38, 17, 568, DateTimeKind.Local).AddTicks(3647)
                        },
                        new
                        {
                            GameId = 38,
                            Descripcion = "Sunt voluptas suscipit pariatur alias est. Deserunt maiores nesciunt esse unde et. Officia nostrum cum et unde a placeat minima.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Practical Rubber Computer",
                            ReleaseDate = new DateTime(2019, 10, 27, 20, 42, 55, 195, DateTimeKind.Local).AddTicks(9996)
                        },
                        new
                        {
                            GameId = 39,
                            Descripcion = "Non tempore mollitia repudiandae et officia in. Dolore facere magnam enim quidem ducimus. Non et blanditiis quae repellendus. Voluptatum dolor ipsum sit.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Gorgeous Frozen Fish",
                            ReleaseDate = new DateTime(2024, 2, 23, 8, 15, 58, 503, DateTimeKind.Local).AddTicks(3856)
                        },
                        new
                        {
                            GameId = 40,
                            Descripcion = "Sit aut dolore est earum assumenda soluta pariatur. Laudantium quo qui et nemo distinctio vel. Reiciendis aliquid et. Magnam alias quaerat perferendis voluptatem architecto. Unde explicabo sed et modi non tempora dignissimos quaerat.",
                            Genero = "Adventure",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Handcrafted Wooden Pizza",
                            ReleaseDate = new DateTime(2015, 11, 16, 17, 5, 14, 387, DateTimeKind.Local).AddTicks(6171)
                        },
                        new
                        {
                            GameId = 41,
                            Descripcion = "Nesciunt cumque rerum qui. Consequatur animi quas consequuntur aut dolores minima aperiam et. Vel aut harum iusto culpa cupiditate fuga. Accusantium repudiandae aut omnis tenetur odio iste odit non.",
                            Genero = "Adventure",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Generic Fresh Computer",
                            ReleaseDate = new DateTime(2016, 11, 10, 4, 38, 48, 146, DateTimeKind.Local).AddTicks(2844)
                        },
                        new
                        {
                            GameId = 42,
                            Descripcion = "Facere labore et enim occaecati. Consequatur eos placeat. Rem ratione molestiae vitae dolores est. Possimus debitis laudantium perferendis tenetur vel quis possimus quos. Enim vel sit. Omnis consequuntur ullam possimus ut iste est similique consequatur.",
                            Genero = "Adventure",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Rustic Granite Pizza",
                            ReleaseDate = new DateTime(2017, 3, 9, 16, 19, 36, 715, DateTimeKind.Local).AddTicks(8024)
                        },
                        new
                        {
                            GameId = 43,
                            Descripcion = "Et ad explicabo amet voluptatem dolores voluptatem omnis recusandae. Officiis dolore repellat pariatur et animi maiores. Corporis quibusdam rem neque consectetur.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Unbranded Steel Keyboard",
                            ReleaseDate = new DateTime(2019, 6, 3, 17, 11, 21, 107, DateTimeKind.Local).AddTicks(9633)
                        },
                        new
                        {
                            GameId = 44,
                            Descripcion = "Quia rem voluptatem. Adipisci sunt mollitia amet nemo quia placeat qui non. Occaecati aut delectus. Non possimus reprehenderit voluptatem.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Handcrafted Plastic Pizza",
                            ReleaseDate = new DateTime(2024, 7, 4, 16, 50, 30, 138, DateTimeKind.Local).AddTicks(9405)
                        },
                        new
                        {
                            GameId = 45,
                            Descripcion = "Voluptates fuga autem quis. Consequatur dicta incidunt praesentium voluptas repellat nostrum cumque nihil delectus. Ea aspernatur quis et eos libero deserunt voluptatem. Quod dolorum quidem sed est maiores similique aperiam. Quis asperiores ea corrupti maxime omnis odio.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Sleek Metal Car",
                            ReleaseDate = new DateTime(2017, 11, 18, 6, 3, 53, 97, DateTimeKind.Local).AddTicks(5107)
                        },
                        new
                        {
                            GameId = 46,
                            Descripcion = "In mollitia natus maiores eligendi. Sit officia ut numquam adipisci ut sit. Consequatur eius illo vel vero ullam sapiente sed ut quidem. Ratione sint voluptatem sit atque non adipisci.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Refined Fresh Hat",
                            ReleaseDate = new DateTime(2016, 9, 21, 21, 59, 24, 798, DateTimeKind.Local).AddTicks(6339)
                        },
                        new
                        {
                            GameId = 47,
                            Descripcion = "Nulla similique fugit nihil laboriosam deserunt. Et maxime est numquam. Sequi ullam ea ipsa et dolorum voluptatem minus repellendus eum. Magni nemo aliquid voluptas aut officiis eaque blanditiis aspernatur id. Et ut placeat quas dignissimos aut omnis delectus aut est. Saepe aut rem animi suscipit voluptas voluptate est qui debitis.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Ergonomic Fresh Ball",
                            ReleaseDate = new DateTime(2023, 12, 9, 19, 29, 30, 131, DateTimeKind.Local).AddTicks(3948)
                        },
                        new
                        {
                            GameId = 48,
                            Descripcion = "Quo nihil laudantium culpa ex quidem. Iure dolorum ut et qui harum illum. Dolor voluptas voluptas. Eveniet mollitia consequatur iusto cum possimus itaque. Eaque quod vel molestias voluptas necessitatibus occaecati eum. Velit ut sint provident et sit nulla.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Tasty Plastic Shirt",
                            ReleaseDate = new DateTime(2023, 7, 21, 14, 8, 51, 254, DateTimeKind.Local).AddTicks(6451)
                        },
                        new
                        {
                            GameId = 49,
                            Descripcion = "Explicabo quam recusandae eos at qui aliquam. Non aliquid qui fugit enim illum. Ducimus tenetur voluptatibus et sit quis provident.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Practical Plastic Soap",
                            ReleaseDate = new DateTime(2020, 3, 23, 10, 19, 14, 82, DateTimeKind.Local).AddTicks(669)
                        },
                        new
                        {
                            GameId = 50,
                            Descripcion = "Dolorum rem adipisci sint. Officiis sunt facere quasi aliquid accusamus. Error eum omnis est neque rerum. Dolores quis recusandae dolorem consequatur.",
                            Genero = "Adventure",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Awesome Soft Gloves",
                            ReleaseDate = new DateTime(2023, 9, 18, 22, 25, 10, 225, DateTimeKind.Local).AddTicks(3799)
                        });
                });

            modelBuilder.Entity("infiniteworlds_frontend.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("EstadoCuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
