// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using infiniteworlds_frontend.Data;

#nullable disable

namespace infiniteworlds_fronted.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240924224052_AddSeeds")]
    partial class AddSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin-id",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7f486c40-675b-4d8d-8293-5f3c10ee3531",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6624e317-19d7-4a86-a973-c51222bfc114",
                            Email = "Monique.Volkman7@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "cuuueeau",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "76f16008-67e6-4496-8e75-06d5ddb718c9",
                            TwoFactorEnabled = false,
                            UserName = "Johnny.Lockman"
                        },
                        new
                        {
                            Id = "e572547d-424d-43eb-9773-feb81c8adba2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b7e82454-4957-4bf9-b328-f2d052fc8412",
                            Email = "Vivianne89@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "beoeooeu",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3e991bb3-ee5b-4b4d-9451-05e89fd16b2c",
                            TwoFactorEnabled = false,
                            UserName = "Maryse_Waters98"
                        },
                        new
                        {
                            Id = "55ab808a-0648-484e-88c9-f0fcc1047b72",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2212b134-74a7-4d5f-91a8-c5696b3309b1",
                            Email = "Winston13@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "diaiaaue",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "739ae6f8-f1af-4059-84df-7d98c670be21",
                            TwoFactorEnabled = false,
                            UserName = "Antwan.Hilpert36"
                        },
                        new
                        {
                            Id = "cf9141f5-85cb-4425-8473-1ede382bbe94",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0443a87b-cef9-4c42-8205-5f91ad699fb5",
                            Email = "Enola_Schultz11@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "qiiuiuuo",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4376b50-78cd-4a57-aaaa-f18922a5729e",
                            TwoFactorEnabled = false,
                            UserName = "Ernie.Hermiston"
                        },
                        new
                        {
                            Id = "d34edeaf-7708-4c1f-aeab-a2bf6bffed8c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "27d0d24a-ea6f-49a0-923f-15019164ede4",
                            Email = "Mckenzie86@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "wueiiooo",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "46e1c0ed-c910-4a04-be64-9133b46333d7",
                            TwoFactorEnabled = false,
                            UserName = "Julien44"
                        },
                        new
                        {
                            Id = "2a7a3e19-d306-451e-8184-b50533fa5546",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e63bff75-fac2-4006-8a75-ee2685ffb457",
                            Email = "Evie.Renner85@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "miueaaeu",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "295cac92-7020-406f-a955-d74b300c52ef",
                            TwoFactorEnabled = false,
                            UserName = "Norris_Effertz91"
                        },
                        new
                        {
                            Id = "aa979614-f233-4ef9-b15a-e05a5435667b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dc3dfef8-e342-4266-9cae-95ff9728e4dc",
                            Email = "Ricardo.Towne@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "kaoouuee",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4aaa6b67-a2a7-49c0-a70b-85ada990fa25",
                            TwoFactorEnabled = false,
                            UserName = "Lawrence_Gleichner"
                        },
                        new
                        {
                            Id = "3f4cf03e-1c7d-45a7-9532-d3d7ac48e0c2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c965762-b84b-4849-8e43-94db853d2fc1",
                            Email = "Remington_Altenwerth@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "hoauueua",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a3432e2c-40df-4383-a26e-67e59c94d584",
                            TwoFactorEnabled = false,
                            UserName = "Adelle.Treutel62"
                        },
                        new
                        {
                            Id = "e279f093-acd5-4649-9cfb-0fca006e7fa6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3602e177-005e-47c4-bbc3-afefe71474db",
                            Email = "Vinnie.Harris@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "coooeioi",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3c1427cc-f8a2-410a-8628-c8039c32ad1c",
                            TwoFactorEnabled = false,
                            UserName = "Rosalinda.Kling"
                        },
                        new
                        {
                            Id = "1436b133-2587-4052-892e-627596af9598",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a723df39-d8a6-4e73-8ce6-80d30f1aea59",
                            Email = "Rocky_Daugherty@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "buioaiuu",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c5a8b12a-3933-4f96-9022-22cb5c277b77",
                            TwoFactorEnabled = false,
                            UserName = "Emanuel.Yundt"
                        },
                        new
                        {
                            Id = "user-admin-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1b9b7e7a-8140-49d8-aae0-31b822c0df03",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEEZlVMC9D6DjIa0wK80kB/myJnNhvq+FaFtPqbqTihiCC4NGBrqM6cT7KVNSr5WMLw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-admin-id",
                            RoleId = "role-admin-id"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("infiniteworlds_fronted.Models.UserProfileViewModel", b =>
                {
                    b.Property<string>("UserProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserProfileId");

                    b.ToTable("userProfileViewModels");
                });

            modelBuilder.Entity("infiniteworlds_frontend.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFilePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Descripcion = "Dolorem expedita fugit illo ut voluptates autem. Voluptas a quaerat voluptatem non dolorem inventore qui. Modi maiores similique vitae. Beatae corporis molestiae dolor asperiores enim sint fugit voluptatibus.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Practical Wooden Chicken",
                            ReleaseDate = new DateTime(2019, 3, 10, 1, 18, 14, 443, DateTimeKind.Local).AddTicks(5436)
                        },
                        new
                        {
                            GameId = 2,
                            Descripcion = "Harum ea sint dolore illo adipisci et. Et quibusdam quo placeat ad qui est cumque quibusdam rem. Quia ipsam vel eveniet. Dolores aut tempora molestiae. Officiis voluptatem voluptatem molestiae voluptatem fugiat velit. Rerum quia aut maxime ut sit expedita.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Awesome Concrete Keyboard",
                            ReleaseDate = new DateTime(2023, 11, 15, 7, 34, 14, 802, DateTimeKind.Local).AddTicks(5208)
                        },
                        new
                        {
                            GameId = 3,
                            Descripcion = "Similique et perferendis tempore id in sunt saepe quam. Excepturi et quia. Maiores voluptatum dolor voluptas sed pariatur eveniet nihil saepe ex. Autem ex fugiat nulla distinctio asperiores nihil natus. Et et impedit eos beatae rerum nihil.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Gorgeous Frozen Computer",
                            ReleaseDate = new DateTime(2022, 11, 8, 2, 24, 22, 945, DateTimeKind.Local).AddTicks(638)
                        },
                        new
                        {
                            GameId = 4,
                            Descripcion = "Repellat est eum non repellendus laborum. Iure enim fugit quam debitis reiciendis harum sed. Quasi quis officiis nesciunt. Laboriosam quo beatae dolores cupiditate sint et quis aut.",
                            Genero = "Adventure",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Generic Metal Chair",
                            ReleaseDate = new DateTime(2015, 7, 30, 11, 37, 41, 264, DateTimeKind.Local).AddTicks(2392)
                        },
                        new
                        {
                            GameId = 5,
                            Descripcion = "Sed quaerat sint velit sunt iusto. Omnis voluptatem et quisquam debitis omnis dolor omnis. Maiores laudantium qui commodi aliquid ut sed iste. Quo et et. Est nostrum omnis ea doloribus atque quo dolor laborum. Ut non quidem quidem a ad.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Generic Wooden Chair",
                            ReleaseDate = new DateTime(2018, 8, 3, 12, 20, 24, 7, DateTimeKind.Local).AddTicks(8658)
                        },
                        new
                        {
                            GameId = 6,
                            Descripcion = "Ratione ea nihil quia similique qui nostrum. Saepe nisi perferendis blanditiis. Quod ut eligendi non. Magnam non temporibus consequuntur nemo corporis quo laudantium accusamus aut. Placeat ut animi maxime maxime repellendus.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Practical Plastic Salad",
                            ReleaseDate = new DateTime(2020, 5, 20, 17, 37, 16, 206, DateTimeKind.Local).AddTicks(429)
                        },
                        new
                        {
                            GameId = 7,
                            Descripcion = "Ut vitae temporibus. Officiis doloremque est tempore. Distinctio molestias blanditiis eos nisi voluptatum odit aut non.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Ergonomic Fresh Car",
                            ReleaseDate = new DateTime(2020, 9, 18, 23, 23, 18, 830, DateTimeKind.Local).AddTicks(2269)
                        },
                        new
                        {
                            GameId = 8,
                            Descripcion = "Ipsa placeat esse. Exercitationem aliquam quam error voluptas ut. Occaecati accusantium fuga iste libero tenetur repudiandae eveniet. Et deserunt nostrum iste a occaecati id delectus dolores nobis.",
                            Genero = "Shooter",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Rustic Frozen Fish",
                            ReleaseDate = new DateTime(2018, 8, 3, 1, 21, 20, 268, DateTimeKind.Local).AddTicks(4841)
                        },
                        new
                        {
                            GameId = 9,
                            Descripcion = "Dolor odit in officia ea sint quo facilis. Qui quod nulla quia. Cupiditate voluptas accusantium nostrum aliquid maxime nesciunt veritatis facilis. Atque eos assumenda dolores sunt tempora alias quia officiis et. Dolorem temporibus rerum. Dolore et velit aut eius voluptatum id ea praesentium.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Small Metal Car",
                            ReleaseDate = new DateTime(2021, 3, 13, 6, 53, 13, 285, DateTimeKind.Local).AddTicks(4663)
                        },
                        new
                        {
                            GameId = 10,
                            Descripcion = "Similique soluta voluptatem sit a. Aut iste molestiae rerum et cumque autem et occaecati. Occaecati fugit velit explicabo. Velit dolores sapiente officiis aliquam quidem praesentium voluptatum quibusdam et. Est doloribus voluptas vitae omnis adipisci error quis aliquid ut.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Licensed Concrete Shirt",
                            ReleaseDate = new DateTime(2022, 11, 12, 8, 6, 37, 41, DateTimeKind.Local).AddTicks(3322)
                        },
                        new
                        {
                            GameId = 11,
                            Descripcion = "Mollitia quaerat pariatur. Corporis asperiores ut accusantium quia. Eius deleniti omnis quibusdam voluptas nobis eos alias. Aut qui totam sed. Atque laborum est. Libero rerum nemo praesentium et quibusdam exercitationem.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Awesome Granite Hat",
                            ReleaseDate = new DateTime(2023, 8, 5, 12, 57, 31, 858, DateTimeKind.Local).AddTicks(1870)
                        },
                        new
                        {
                            GameId = 12,
                            Descripcion = "Repellendus odit consequuntur aut dolorem qui cumque error. Aspernatur et ad sit. Soluta nostrum sed. Nobis in repellendus alias quia temporibus ut. Voluptatem harum non est facere vitae.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Licensed Rubber Car",
                            ReleaseDate = new DateTime(2019, 11, 22, 16, 28, 57, 936, DateTimeKind.Local).AddTicks(1704)
                        },
                        new
                        {
                            GameId = 13,
                            Descripcion = "Dignissimos corporis minus officiis. Quibusdam sit debitis deserunt nisi et quo nulla. Blanditiis nihil dolor repudiandae eveniet assumenda error laboriosam. Ipsa nemo est nihil et sint sunt.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Tasty Metal Fish",
                            ReleaseDate = new DateTime(2020, 2, 8, 6, 23, 31, 850, DateTimeKind.Local).AddTicks(6444)
                        },
                        new
                        {
                            GameId = 14,
                            Descripcion = "Labore explicabo numquam consequatur sapiente. Qui provident mollitia modi quia maxime quasi. Voluptatum fugit aut et error corporis labore optio. Veritatis dolores nobis et voluptatem.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Incredible Concrete Salad",
                            ReleaseDate = new DateTime(2022, 2, 22, 12, 45, 10, 93, DateTimeKind.Local).AddTicks(3955)
                        },
                        new
                        {
                            GameId = 15,
                            Descripcion = "Omnis odio libero in corrupti quo voluptas omnis. Sunt possimus ducimus. Explicabo nobis occaecati non aperiam veritatis non dolor vitae. Necessitatibus aut illum aliquid. Itaque qui quaerat libero laboriosam corrupti sequi eveniet.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Incredible Plastic Fish",
                            ReleaseDate = new DateTime(2019, 7, 3, 21, 24, 49, 905, DateTimeKind.Local).AddTicks(8285)
                        },
                        new
                        {
                            GameId = 16,
                            Descripcion = "Facilis vitae inventore quia tempore beatae. Ut soluta earum consequatur dolor et quia tempora et. Dolorem placeat iste. Mollitia quo enim. Minima in laudantium beatae et commodi nulla ex fuga et. Aspernatur rerum dolore dolorem enim eveniet doloremque.",
                            Genero = "Action",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Sleek Cotton Mouse",
                            ReleaseDate = new DateTime(2021, 7, 25, 16, 35, 44, 82, DateTimeKind.Local).AddTicks(4220)
                        },
                        new
                        {
                            GameId = 17,
                            Descripcion = "Dolorem non illo nesciunt saepe. Architecto esse est illum fuga. Neque eum fugit debitis et quisquam ea enim vel. Assumenda sunt recusandae praesentium placeat quam rerum sed. Excepturi dolores numquam exercitationem illum non.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Gorgeous Concrete Ball",
                            ReleaseDate = new DateTime(2020, 5, 15, 21, 33, 7, 985, DateTimeKind.Local).AddTicks(6919)
                        },
                        new
                        {
                            GameId = 18,
                            Descripcion = "Error totam iure veniam fuga nostrum alias quia. Hic expedita eius. Est qui voluptas nulla non quo. Non commodi mollitia eaque provident quis.",
                            Genero = "Adventure",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Licensed Frozen Hat",
                            ReleaseDate = new DateTime(2023, 2, 8, 12, 39, 47, 840, DateTimeKind.Local).AddTicks(9845)
                        },
                        new
                        {
                            GameId = 19,
                            Descripcion = "Fuga dolorem facere aut error est est dolor ut. Ducimus consequatur sint in facere fuga deserunt explicabo quidem. Exercitationem quibusdam molestias doloribus ipsam dolorem veritatis quo laborum. Laborum rerum voluptates ut. Amet sit sit et dolore quis repudiandae laudantium iure. Iusto velit voluptatem repellendus reprehenderit nihil.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Generic Metal Shoes",
                            ReleaseDate = new DateTime(2023, 3, 17, 14, 24, 4, 392, DateTimeKind.Local).AddTicks(6199)
                        },
                        new
                        {
                            GameId = 20,
                            Descripcion = "Vel illo ea et perspiciatis fugit. Voluptatum veritatis ad est voluptatem distinctio adipisci modi. Fuga rerum pariatur omnis eligendi accusamus ducimus et. Corporis dolor pariatur dolore voluptates. Voluptas et natus.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Practical Cotton Chips",
                            ReleaseDate = new DateTime(2016, 8, 25, 5, 50, 2, 873, DateTimeKind.Local).AddTicks(4081)
                        },
                        new
                        {
                            GameId = 21,
                            Descripcion = "Hic autem architecto. Enim modi voluptatem qui aspernatur. Voluptates minus esse explicabo ratione perspiciatis qui accusamus. Quis autem sed.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Handmade Granite Chips",
                            ReleaseDate = new DateTime(2018, 8, 9, 8, 43, 9, 294, DateTimeKind.Local).AddTicks(2664)
                        },
                        new
                        {
                            GameId = 22,
                            Descripcion = "Quis esse asperiores ut aut fugiat laudantium mollitia. Possimus id assumenda voluptatem nemo voluptatem. Saepe ab dolorem et iste aliquid illo. At magnam quidem consequatur ipsum.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Generic Metal Gloves",
                            ReleaseDate = new DateTime(2017, 9, 8, 1, 14, 35, 702, DateTimeKind.Local).AddTicks(8042)
                        },
                        new
                        {
                            GameId = 23,
                            Descripcion = "Et voluptatem ullam. Maxime asperiores eos corrupti dolor consectetur aperiam dolorem neque. Eos nemo non quos qui dolor voluptatibus. Alias qui provident ipsa molestiae id ipsum illo odit. Dolorem saepe in temporibus nemo sit recusandae est alias. Ducimus deserunt inventore dignissimos consectetur.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Practical Steel Cheese",
                            ReleaseDate = new DateTime(2020, 3, 4, 18, 43, 19, 599, DateTimeKind.Local).AddTicks(5612)
                        },
                        new
                        {
                            GameId = 24,
                            Descripcion = "Quaerat perferendis hic atque. Tenetur nihil ad velit alias id facere tempora. Nihil iste voluptas vero minus fugit. Unde qui deserunt quis eligendi quia. Est rerum voluptatem blanditiis incidunt qui.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Rustic Rubber Chips",
                            ReleaseDate = new DateTime(2022, 11, 14, 1, 18, 43, 307, DateTimeKind.Local).AddTicks(6173)
                        },
                        new
                        {
                            GameId = 25,
                            Descripcion = "Quis sed odit veniam dicta quia sit sed veritatis. At ipsa quia. Non laudantium culpa voluptatibus maiores non corporis et dolorem.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Handmade Frozen Bike",
                            ReleaseDate = new DateTime(2016, 1, 7, 12, 47, 4, 149, DateTimeKind.Local).AddTicks(7076)
                        },
                        new
                        {
                            GameId = 26,
                            Descripcion = "Vel itaque rerum. Libero optio aspernatur voluptatem. Voluptate dicta non quia sapiente id. Iure nostrum nihil sunt sed. Commodi est accusamus aut. Voluptates sequi magnam sit.",
                            Genero = "Action",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Handcrafted Fresh Cheese",
                            ReleaseDate = new DateTime(2018, 6, 30, 18, 38, 17, 323, DateTimeKind.Local).AddTicks(4003)
                        },
                        new
                        {
                            GameId = 27,
                            Descripcion = "Ad asperiores quis explicabo doloremque. Placeat rerum voluptas cumque. Nihil ut aliquid quis cum. Iusto nam inventore dolorem dignissimos qui non odio. Velit vitae exercitationem molestiae sit repellendus sed deserunt aspernatur. Eveniet sit aut laborum enim rem veritatis deserunt.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Incredible Granite Pants",
                            ReleaseDate = new DateTime(2018, 11, 15, 7, 7, 32, 798, DateTimeKind.Local).AddTicks(7141)
                        },
                        new
                        {
                            GameId = 28,
                            Descripcion = "Et ut fugiat fugiat natus maxime natus architecto voluptate in. Veritatis nostrum modi aut facere enim consectetur nobis. Ducimus eum quia autem in voluptatem velit fuga iusto quibusdam. Quaerat vel officiis vitae vitae. Voluptatibus tempora et praesentium et. Vel eius recusandae.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Generic Rubber Car",
                            ReleaseDate = new DateTime(2021, 10, 26, 2, 27, 20, 919, DateTimeKind.Local).AddTicks(6201)
                        },
                        new
                        {
                            GameId = 29,
                            Descripcion = "Exercitationem quae impedit minus non ducimus ducimus a commodi expedita. Sapiente nesciunt ullam. Porro assumenda vel distinctio. Tempora magni a veritatis mollitia beatae minima architecto.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Refined Cotton Mouse",
                            ReleaseDate = new DateTime(2016, 10, 11, 9, 1, 3, 663, DateTimeKind.Local).AddTicks(5455)
                        },
                        new
                        {
                            GameId = 30,
                            Descripcion = "Neque commodi illo sint sed. Iste inventore quos. Cumque necessitatibus ut quisquam. Et quia est ut mollitia. Nulla eos cum rem.",
                            Genero = "Shooter",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Handcrafted Metal Bacon",
                            ReleaseDate = new DateTime(2016, 2, 12, 21, 55, 40, 228, DateTimeKind.Local).AddTicks(5465)
                        },
                        new
                        {
                            GameId = 31,
                            Descripcion = "Impedit unde fugiat porro quo. Harum sequi velit. Delectus odit aut eum vel. Aut eligendi ut consectetur eum dolorem error sed fugiat odit. Maxime iusto nihil voluptatibus.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Gorgeous Frozen Tuna",
                            ReleaseDate = new DateTime(2021, 6, 4, 12, 31, 45, 20, DateTimeKind.Local).AddTicks(7209)
                        },
                        new
                        {
                            GameId = 32,
                            Descripcion = "Rerum ipsa rerum est. Accusantium amet voluptatem est a. Distinctio voluptatem vel laborum necessitatibus. Perspiciatis architecto unde cumque et voluptas iusto reprehenderit.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Incredible Steel Chips",
                            ReleaseDate = new DateTime(2018, 6, 28, 18, 51, 23, 318, DateTimeKind.Local).AddTicks(5816)
                        },
                        new
                        {
                            GameId = 33,
                            Descripcion = "Pariatur sequi rerum voluptatem aut sed blanditiis dolorum voluptatem voluptate. Aut consequatur animi aut est provident asperiores unde. Iste in distinctio quidem. Qui magni porro nobis optio qui voluptatum.",
                            Genero = "Shooter",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Generic Steel Cheese",
                            ReleaseDate = new DateTime(2022, 3, 2, 11, 30, 28, 68, DateTimeKind.Local).AddTicks(5274)
                        },
                        new
                        {
                            GameId = 34,
                            Descripcion = "Eum sunt similique voluptatem. Rerum qui neque dolor quod minus. Ea provident velit quos ipsa qui commodi. Cum nulla recusandae at eligendi. Culpa debitis eum eaque iste.",
                            Genero = "Action",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Generic Rubber Cheese",
                            ReleaseDate = new DateTime(2016, 1, 12, 14, 57, 50, 192, DateTimeKind.Local).AddTicks(6713)
                        },
                        new
                        {
                            GameId = 35,
                            Descripcion = "Nisi voluptates est. Dolorem id aliquam sed asperiores dolores rerum in. Eligendi quia iure itaque necessitatibus voluptatem et veritatis. Harum qui nemo qui harum delectus magnam harum velit laudantium. Eum tenetur odio saepe accusantium ut amet officiis et vel.",
                            Genero = "Shooter",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Awesome Cotton Gloves",
                            ReleaseDate = new DateTime(2017, 7, 24, 23, 57, 40, 282, DateTimeKind.Local).AddTicks(9910)
                        },
                        new
                        {
                            GameId = 36,
                            Descripcion = "Id rerum eligendi sit deleniti aut. Ad ea voluptas omnis a exercitationem totam. Vitae temporibus laboriosam et et velit accusamus.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Refined Steel Pizza",
                            ReleaseDate = new DateTime(2024, 7, 30, 13, 27, 44, 770, DateTimeKind.Local).AddTicks(1374)
                        },
                        new
                        {
                            GameId = 37,
                            Descripcion = "Qui soluta temporibus voluptate error saepe voluptates sit. Maxime ipsum autem vel dicta dignissimos eaque atque. Dolor et ea alias iure sunt impedit assumenda. Minima quas nihil sit. Qui unde consequatur cupiditate delectus ipsam a esse animi sit.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Small Soft Chicken",
                            ReleaseDate = new DateTime(2022, 9, 28, 3, 16, 8, 770, DateTimeKind.Local).AddTicks(5382)
                        },
                        new
                        {
                            GameId = 38,
                            Descripcion = "Architecto quidem qui non. Voluptatum aut vitae repellendus soluta temporibus eligendi ex. Tempore maxime ut odit.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Incredible Wooden Shoes",
                            ReleaseDate = new DateTime(2020, 4, 25, 8, 12, 2, 625, DateTimeKind.Local).AddTicks(2865)
                        },
                        new
                        {
                            GameId = 39,
                            Descripcion = "Laborum quia similique nisi. Accusantium impedit dolores necessitatibus illum in voluptatem sunt voluptatum. Sit aut nulla repellendus beatae sit et.",
                            Genero = "RPG",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Handmade Steel Chair",
                            ReleaseDate = new DateTime(2015, 5, 8, 20, 45, 56, 971, DateTimeKind.Local).AddTicks(2612)
                        },
                        new
                        {
                            GameId = 40,
                            Descripcion = "Saepe iste soluta. Itaque incidunt ipsum maiores nesciunt quae ab quia dolore corrupti. Quia quisquam vitae. Reprehenderit error cum perferendis commodi quo sed eos. Sit aperiam in assumenda itaque. Et ut itaque eum voluptate qui temporibus atque.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Tasty Steel Pants",
                            ReleaseDate = new DateTime(2020, 3, 28, 18, 50, 34, 274, DateTimeKind.Local).AddTicks(3555)
                        },
                        new
                        {
                            GameId = 41,
                            Descripcion = "Perspiciatis eius qui. Facilis id adipisci nihil voluptas magni nobis. Voluptatem enim in reprehenderit nesciunt accusamus adipisci facere aut. Repellendus perspiciatis et molestiae sit impedit excepturi velit. Id aperiam in dicta rerum quaerat nemo.",
                            Genero = "Action",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Unbranded Concrete Computer",
                            ReleaseDate = new DateTime(2016, 1, 31, 6, 19, 5, 847, DateTimeKind.Local).AddTicks(6417)
                        },
                        new
                        {
                            GameId = 42,
                            Descripcion = "Eveniet harum totam vel impedit magnam ullam. Nihil fuga alias repudiandae saepe eius officiis quos dignissimos quis. Molestiae commodi voluptatum est. Sunt eligendi voluptatum. Pariatur placeat dolore rerum dolorem hic.",
                            Genero = "Adventure",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Intelligent Fresh Ball",
                            ReleaseDate = new DateTime(2021, 7, 18, 2, 49, 59, 231, DateTimeKind.Local).AddTicks(9414)
                        },
                        new
                        {
                            GameId = 43,
                            Descripcion = "Expedita a sit sint. Explicabo minima molestias blanditiis deserunt eaque a rerum necessitatibus sit. Omnis aperiam tenetur saepe dignissimos commodi dolores magnam quidem. Et maxime quod modi eum dolore assumenda officiis numquam modi.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Handmade Concrete Shirt",
                            ReleaseDate = new DateTime(2018, 9, 24, 11, 42, 55, 322, DateTimeKind.Local).AddTicks(892)
                        },
                        new
                        {
                            GameId = 44,
                            Descripcion = "Aliquid quia ut ea quia totam. Voluptatem ullam nesciunt tenetur reprehenderit repudiandae. Explicabo placeat rem suscipit. Ut adipisci molestias esse quo eum. Reiciendis sint dolorum in praesentium. Eos ut ipsum accusantium quia et fuga nobis et.",
                            Genero = "Shooter",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Rustic Soft Tuna",
                            ReleaseDate = new DateTime(2023, 6, 17, 14, 23, 14, 425, DateTimeKind.Local).AddTicks(2823)
                        },
                        new
                        {
                            GameId = 45,
                            Descripcion = "Qui quo accusantium et beatae maxime doloremque porro. Inventore quia accusantium doloremque enim aut. Harum animi et molestias blanditiis tempora eos. Eos repellat sit aut eaque modi cupiditate voluptatem quia.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Small Fresh Gloves",
                            ReleaseDate = new DateTime(2023, 3, 22, 9, 38, 3, 600, DateTimeKind.Local).AddTicks(5897)
                        },
                        new
                        {
                            GameId = 46,
                            Descripcion = "Eos dolor aliquid aliquid a aut. Et qui error. A nulla et ipsam at.",
                            Genero = "Shooter",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Gorgeous Cotton Car",
                            ReleaseDate = new DateTime(2016, 7, 1, 4, 24, 43, 994, DateTimeKind.Local).AddTicks(3340)
                        },
                        new
                        {
                            GameId = 47,
                            Descripcion = "Quisquam totam aperiam cumque magni dolorem. Quo ullam et id enim ab culpa quis. Voluptatum rerum iusto similique magnam quod. Autem in ducimus delectus quo pariatur quia quasi animi rem.",
                            Genero = "Strategy",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Generic Fresh Shoes",
                            ReleaseDate = new DateTime(2022, 6, 26, 19, 33, 3, 930, DateTimeKind.Local).AddTicks(3297)
                        },
                        new
                        {
                            GameId = 48,
                            Descripcion = "Eos quasi molestiae amet. Laborum quisquam molestias quo. Cum labore libero.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Intelligent Concrete Fish",
                            ReleaseDate = new DateTime(2020, 1, 6, 11, 35, 42, 417, DateTimeKind.Local).AddTicks(4517)
                        },
                        new
                        {
                            GameId = 49,
                            Descripcion = "Voluptate dolore inventore optio reprehenderit. Voluptatem expedita consectetur odio ratione sequi. Aut autem earum dignissimos. Voluptatibus dolores dolore omnis pariatur voluptatem officiis.",
                            Genero = "Puzzle",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Incredible Fresh Sausages",
                            ReleaseDate = new DateTime(2014, 12, 13, 12, 36, 49, 571, DateTimeKind.Local).AddTicks(1594)
                        },
                        new
                        {
                            GameId = 50,
                            Descripcion = "Molestias vero qui perspiciatis. Et nam placeat aliquam perspiciatis ipsa molestias. Pariatur distinctio quas iure excepturi saepe. Ipsam voluptates rem mollitia et possimus laboriosam. Est facere corporis veritatis. Et voluptatem dolor aliquam repellat officiis.",
                            Genero = "Shooter",
                            ImageFilePath = "https://picsum.photos/200/300",
                            Name = "Handcrafted Cotton Tuna",
                            ReleaseDate = new DateTime(2021, 11, 24, 3, 29, 52, 243, DateTimeKind.Local).AddTicks(2371)
                        });
                });

            modelBuilder.Entity("infiniteworlds_frontend.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("EstadoCuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
