version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Jcdo1096@"
      ACCEPT_EULA: "Y"
    networks:
      - app-network

  app:
    build: .
    networks:
      - app-network

networks:
  app-network:
    driver: bridge




